version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    volumes:
      - ../:/workspace:cached
    command: sleep infinity
    depends_on:
      - db
    networks:
      - internal_network
      - external_network

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
      args:
        - VARIANT=20
    volumes:
      - ../:/workspace:cached
    command: sleep infinity
    networks:
      - internal_network
      - external_network
    depends_on:
      - turborepo-cache
      - redis

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: imf
      POSTGRES_USER: imf
      POSTGRES_PASSWORD: imf
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - internal_network

  turborepo-cache:
    image: ducktors/turborepo-remote-cache:2.0.8
    #ports:
    #- "6000:6000"
    environment:
      - TURBO_TOKEN=${TURBO_TOKEN}
      - REDIS_URL=redis://redis:6379
    restart: unless-stopped
    networks:
      - internal_network

  redis:
    image: redis:alpine
    #ports:
    #  - "6379:6379"
    restart: unless-stopped
    networks:
      - internal_network

volumes:
  postgres_data:

networks:
  internal_network:
    internal: true
  external_network:
